services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always

  bridge-service:
    image: python:3.9-slim
    volumes:
      - ./bridge.py:/app/bridge.py
    working_dir: /app
    tty: true
    stdin_open: true
    command: ["sh", "-c", "pip install paho-mqtt influxdb-client && python -u bridge.py"]
    depends_on:
      - mqtt
      - influxdb

  simulator:
    image: python:3.9-slim
    volumes:
      - ./simulator.py:/app/simulator.py
    working_dir: /app
    command: ["sh", "-c", "pip install paho-mqtt && python -u simulator.py"]
    depends_on:
      - mqtt

volumes:
  influxdb_data: